### PR TITLE
Update development-updates.md Week15

### PR DESCRIPTION
**Pull request by rose2221**

### CODE REVIEW

**Comment by taxmeifyoucan** [comment]
You don't need to open a new PR, just push updates to the right branch :)

**Comment by taxmeifyoucan** [comment]
And reading the update now, it's pretty short so you could also merge it into a single document.

**Comment by rose2221** [comment]
Should i explain the code that i wrote in the PR for TLS Protocol tests?

**Comment by taxmeifyoucan** [comment]
Sure I believe you can elaborate on that! But the update should mainly serve **you** Rose, it's for you to collect your thoughts, write down what you learned and how your process works when working on this. So feel free to explain anything you find important, I don't really want to guide you here :)

**Pull request closed without merging**
