### PR TITLE
Week13 updated added 

### PR DESCRIPTION
**Pull request by Redidacove**
Week 13 update is ready to merge 🟣
Thanks in advance 🙏🏻

### CODE REVIEW

**Comment by taxmeifyoucan** [comment]
Thanks for the update! It mentions PRs you are working on but no link or further context. Can you please link them and maybe elaborate on where the PR fits in the project, what was the feedback you received, etc

**Comment by Redidacove** [comment]
> Thanks for the update! It mentions PRs you are working on but no link or further context. Can you please link them and maybe elaborate on where the PR fits in the project, what was the feedback you received, etc

sure thing sorry for that

**Comment by Redidacove** [comment]
Updated 💯

**Comment by Redidacove** [comment]
messed up this due to rebase branch ig let me open another

**Pull request closed without merging**
